title:              "Intelligence artificielle : Art et Création"
email:              ravi.hassanaly@ecl16.ec-lyon.fr
description:        "Synthèse de la veille technologique réaliser dans la cadre du cours Nouvelles Technologies de l'Information et de la Communication à l'Ecole Centrale Lyon"
author:             Ravi Hassanaly
baseurl:            "/vtecl"
url:                "https://ravih18.github.io"

# Social Profiles
twitter_username:   "@HassanalyRavi"
github_username:    ravih18
facebook_username:  ""
linkedin_username:  "rhassana"

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
future:             true
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
